version: '3'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: api
    # environment:
    #   DB_HOST: postgres
    #   DB_PORT: 5432
    #   DB_URL: postgres://root@postgres/root?sslmode=disable
    ports:
      - '8080:80'

  postgres:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_USER: root

