version: '3'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: api
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PORT: 5432
      DB_PASSWORD: dbpassword
      DB_SCHEMA: analytics
    ports:
      - '8080:80'

  static:
    build:
      context: .
      dockerfile: docker/Dockerfile.static
    container_name: static
    ports:
      - '8888:80'

  postgres:
    build:
      context: .
      dockerfile: docker/Dockerfile.db
    container_name: db
    environment:
      POSTGRES_PASSWORD: dbpassword

