version: 2

# Save prerequisites cache using pattern from https://circleci.com/docs/2.0/caching/
save_cache: &save_cache
  key: cache-v1-{{ .Branch }}-{{ checksum "backend/poetry.lock" }}-{{ checksum "frontend/yarn.lock" }}
  paths:
    - /root/.cache
    - /home/circleci/.cache

# Restore saved prerequisites cache using pattern from https://circleci.com/docs/2.0/caching/
restore_cache: &restore_cache
  keys:
    # when lock file changes, use increasingly general patterns to restore cache
    - cache-v1-{{ .Branch }}-{{ checksum "backend/poetry.lock" }}-{{ checksum "frontend/yarn.lock" }}
    - cache-v1-{{ .Branch }}-{{ checksum "backend/poetry.lock" }}-
    - cache-v1-{{ .Branch }}-
    - cache-v1-

jobs:
  build:
    docker:
      - image: circleci/python:3.7.2-node-browsers
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache
      - run:
          name: Setup poetry
          command: sudo pip install poetry
      - run:
          name: Install dependencies
          command: make install
      - save_cache:
          <<: *save_cache
      - run:
          name: Lint all code
          command: make lint
      - run:
          name: Run unit tests
          command: make test-unit
      - setup_remote_docker
      - run:
          name: Bring up all docker containers and test network reachability
          command: |
            set -x
            docker-compose up -d
            docker run --network container:api appropriate/curl \
              -s --retry 10 --retry-delay 1 --retry-connrefused http://localhost:80/
            echo all is up
      - run:
          name: Run integration tests
          command: make test-integration

  deploy:
    docker:
      - image: circleci/python:3.7.2-node-browsers
    steps:
      - run:
          name: Push to ECR
          command: |
            set -x
            echo Pushing


# Default workflow filter to trigger on PR
filter_PR: &filter_PR
  filters:
    branches:
      only:
        - /^.*MAF-.*/
# Default workflow filter to trigger on master branch
filter_merge: &filter_master
  filters:
    branches:
      only:
        - master
# Default workflow filter to trigger on PR and master branches
branch_filters: &filter_master_and_PR
  filters:
    branches:
      only:
        - /^.*MAF-.*/
        - master

# This syntax is from CircleCI 1.0 but it works on 2.0 per
# https://discuss.circleci.com/t/experimental-branch-notifications-from-1-0/12964
experimental:
  notify:
    branches:
      only:
        - master

workflows:
  version: 2
  mafpoc:
    jobs:
      - build:
          <<: *filter_master_and_PR
      - deploy:
          <<: *filter_master
          requires:
            - build

