version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
      # - image: circleci/postgres:11.1-alpine
      #   environment:
      #     POSTGRES_USER: root
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build all docker containers
          command: docker-compose build


  test:
    docker:
      - image: circleci/python:3.7.2-node-browsers
    steps:
      - run:
          name: Bring up all docker containers and test network reachability
          command: |
            set -x
            docker-compose up -d
            docker run --network container:api appropriate/curl \
              --retry 10 --retry-delay 1 --retry-connrefused http://localhost:8080/
      - run:
          name: Run all tests
          command: make test
      - run:
          name: Lint all code
          command: make lint

  deploy:
    docker:
      - image: circleci/python:3.7.2-node-browsers
    steps:
      - run:
          name: Push to ECR
          command: |
            set -x
            echo Pushing


# Default workflow filter to trigger on PR
filter_PR: &filter_PR
  filters:
    branches:
      only:
        - /^MAF-.*/
# Default workflow filter to trigger on master branch
filter_merge: &filter_merge
  filters:
    branches:
      only:
        - master
# Default workflow filter to trigger on PR and master branches
branch_filters: &filter_master_and_PR
  filters:
    branches:
      only:
        - /^MAF-.*/
        - master

# This syntax is from CircleCI 1.0 but it works on 2.0 per
# https://discuss.circleci.com/t/experimental-branch-notifications-from-1-0/12964
experimental:
  notify:
    branches:
      only:
        - master

workflows:
  version: 2
  mafpoc:
    jobs:
      - build:
          <<: *filter_master_and_PR
      - test:
          <<: *filter_master_and_PR
          requires:
            - build
      - deploy:
          <<: *filter_master
          requires:
            - test

