FROM python:3.7.2-alpine3.9
LABEL maintainer="Radoslav Sandov <rsandov@softserveinc.com>"

RUN apk add --no-cache --virtual .build-deps gcc libc-dev \
    && pip install poetry meinheld gunicorn \
    && apk del .build-deps gcc libc-dev

COPY ./docker/gunicorn_conf.py ./docker/entrypoint.sh /
RUN chmod +x /entrypoint.sh && mkdir /app

WORKDIR /app/

COPY ./backend/pyproject.toml ./backend/poetry.lock /app/

RUN poetry config settings.virtualenvs.create false && poetry install --no-dev

COPY ./backend/app /app/app
COPY ./backend/config/test.db /tmp/test.db
# COPY ./backend/migrations/migrations.py /app/migrations.py
# RUN python /app/migrations.py

EXPOSE 80

ENTRYPOINT ["/entrypoint.sh"]
