FROM python:3.7-alpine3.9
LABEL maintainer="Eugene Yunak <yyunak@softserveinc.com>"

RUN apk add --no-cache --virtual .build-deps gcc libc-dev \
    && pip install poetry meinheld gunicorn \
    && apk del .build-deps gcc libc-dev

COPY ./docker/gunicorn_conf.py /gunicorn_conf.py
COPY ./docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh && mkdir /app

WORKDIR /app/
#COPY ./backend/poetry.lock /app
COPY ./backend/pyproject.toml ./backend/poetry.lock /app/
RUN poetry config settings.virtualenvs.create false && poetry install --no-dev

COPY ./backend/api /app/api

EXPOSE 80

ENTRYPOINT ["/entrypoint.sh"]
